services:
  - type: web
    name: weatherstack-go
    env: go
    rootDir: .
    buildCommand: go build -o main ./cmd/server
    startCommand: ./main
    envVars:
      - key: GO_VERSION
        value: 1.25.3
      - key: OPENWEATHER_API_KEY
        sync: false
